# Turkish translation for engine
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the engine package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: engine\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2011-02-21 10:03-0500\n"
"PO-Revision-Date: 2011-12-14 18:10+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Turkish <tr@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2011-12-15 05:54+0000\n"
"X-Generator: Launchpad (build 14487)\n"

#: ../engine/scheduler/chance.py:37 ../engine/scheduler/zone.py:55
#: ../engine/scheduler/simple.py:75 ../engine/scheduler/simple.py:110
#: ../engine/scheduler/simple.py:122
msgid "No hosts found"
msgstr ""

#: ../engine/exception.py:54
msgid "Unexpected error while running command."
msgstr ""

#: ../engine/exception.py:57
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: ../engine/exception.py:107
msgid "DB exception wrapped"
msgstr ""

#. exc_type, exc_value, exc_traceback = sys.exc_info()
#: ../engine/exception.py:127
msgid "Uncaught exception"
msgstr ""

#: ../engine/volume/api.py:45
#, python-format
msgid "Quota exceeeded for %(pid)s, tried to create %(size)sG volume"
msgstr ""

#: ../engine/volume/api.py:57
#, python-format
msgid "Volume quota exceeded. You cannot create a volume of size %sG"
msgstr ""

#: ../engine/volume/api.py:102 ../engine/volume/api.py:172
#: ../engine/volume/api.py:230
msgid "Volume status must be available"
msgstr ""

#: ../engine/volume/api.py:174
msgid "Volume is already attached"
msgstr ""

#: ../engine/volume/api.py:180
msgid "Volume is already detached"
msgstr ""

#: ../engine/api/x7/servers.py:72
msgid "Failed to read private ip"
msgstr ""

#: ../engine/api/x7/servers.py:79
msgid "Failed to read public ip(s)"
msgstr ""

#: ../engine/api/x7/servers.py:152
#, python-format
msgid "%(param)s property not found for image %(_image_id)s"
msgstr ""

#: ../engine/api/x7/servers.py:168
msgid "No keypairs defined"
msgstr ""

#: ../engine/api/x7/v2/contrib/admin_actions.py:165
#, python-format
msgid "Compute.api::lock %s"
msgstr ""

#: ../engine/api/x7/v2/contrib/admin_actions.py:182
#, python-format
msgid "Compute.api::unlock %s"
msgstr ""

#: ../engine/api/x7/servers.py:388
#, python-format
msgid "Compute.api::get_lock %s"
msgstr ""

#: ../engine/api/x7/v2/contrib/admin_actions.py:131
#, python-format
msgid "Compute.api::reset_network %s"
msgstr ""

#: ../engine/api/x7/v2/contrib/admin_actions.py:59
#, python-format
msgid "Compute.api::pause %s"
msgstr ""

#: ../engine/api/x7/v2/contrib/admin_actions.py:74
#, python-format
msgid "Compute.api::unpause %s"
msgstr ""

#: ../engine/api/x7/v2/contrib/admin_actions.py:89
#, python-format
msgid "compute.api::suspend %s"
msgstr ""

#: ../engine/api/x7/v2/contrib/admin_actions.py:104
#, python-format
msgid "compute.api::resume %s"
msgstr ""

#: ../engine/virt/xenapi/volumeops.py:48 ../engine/virt/xenapi/volumeops.py:101
#: ../engine/db/sqlalchemy/api.py:731 ../engine/virt/libvirt_conn.py:741
#: ../engine/api/ec2/__init__.py:317
#, python-format
msgid "Instance %s not found"
msgstr ""

#. NOTE: No Resource Pool concept so far
#: ../engine/virt/xenapi/volumeops.py:50
#, python-format
msgid "Attach_volume: %(instance_name)s, %(device_path)s, %(mountpoint)s"
msgstr ""

#: ../engine/virt/xenapi/volumeops.py:174
#, python-format
msgid "Unable to create VDI on SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""

#: ../engine/virt/xenapi/volumeops.py:187
#, python-format
msgid "Unable to use SR %(sr_ref)s for instance %(instance_name)s"
msgstr ""

#: ../engine/virt/xenapi/volumeops.py:195
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr ""

#: ../engine/virt/xenapi/volumeops.py:198
#, python-format
msgid "Mountpoint %(mountpoint)s attached to instance %(instance_name)s"
msgstr ""

#. Detach VBD from VM
#: ../engine/virt/xenapi/volumeops.py:208
#, python-format
msgid "Detach_volume: %(instance_name)s, %(mountpoint)s"
msgstr ""

#: ../engine/virt/xenapi/volumeops.py:216
#, python-format
msgid "Unable to locate volume %s"
msgstr ""

#: ../engine/virt/xenapi/volumeops.py:224
#, python-format
msgid "Unable to detach volume %s"
msgstr ""

#: ../engine/virt/xenapi/volumeops.py:238
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""

#: ../engine/compute/instance_types.py:115 ../engine/compute/instance_types.py:127
#: ../engine/compute/instance_types.py:141 ../engine/compute/instance_types.py:152
#, python-format
msgid "Unknown instance type: %s"
msgstr ""

#: ../engine/crypto.py:50
msgid "Filename of root CA"
msgstr ""

#: ../engine/crypto.py:53
msgid "Filename of private key"
msgstr ""

#: ../engine/crypto.py:55
msgid "Filename of root Certificate Revokation List"
msgstr ""

#: ../engine/crypto.py:57
msgid "Where we keep our keys"
msgstr ""

#: ../engine/crypto.py:59
msgid "Where we keep our root CA"
msgstr ""

#: ../engine/crypto.py:61
msgid "Should we use a CA for each project?"
msgstr ""

#: ../engine/crypto.py:65
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr ""

#: ../engine/crypto.py:70
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr ""

#: ../engine/crypto.py:75
#, python-format
msgid "Subject for certificate for vpns, %s for project, timestamp"
msgstr ""

#: ../engine/crypto.py:277
#, python-format
msgid "Flags path: %s"
msgstr ""

#: ../engine/scheduler/manager.py:69
#, python-format
msgid "Casting to %(topic)s %(host)s for %(method)s"
msgstr ""

#: ../engine/compute/manager.py:101
#, python-format
msgid "check_instance_lock: decorating: |%s|"
msgstr ""

#: ../engine/compute/manager.py:104
#, python-format
msgid ""
"check_instance_lock: arguments: |%(self)s| |%(context)s| |%(instance_id)s|"
msgstr ""

#: ../engine/compute/manager.py:107
#, python-format
msgid "check_instance_lock: locked: |%s|"
msgstr ""

#: ../engine/compute/manager.py:109
#, python-format
msgid "check_instance_lock: admin: |%s|"
msgstr ""

#: ../engine/compute/manager.py:114
#, python-format
msgid "check_instance_lock: executing: |%s|"
msgstr ""

#: ../engine/compute/manager.py:118
#, python-format
msgid "check_instance_lock: not executing |%s|"
msgstr ""

#: ../engine/compute/manager.py:334
msgid "Instance has already been created"
msgstr ""

#: ../engine/compute/manager.py:391
#, python-format
msgid "instance %s: starting..."
msgstr ""

#: ../engine/virt/xenapi/vmops.py:216
#, python-format
msgid "instance %s: Failed to spawn"
msgstr ""

#: ../engine/compute/manager.py:233 ../engine/tests/test_cloud.py:286
#, python-format
msgid "Terminating instance %s"
msgstr ""

#: ../engine/compute/manager.py:255
#, python-format
msgid "Deallocating address %s"
msgstr ""

#: ../engine/compute/manager.py:524
#, python-format
msgid "trying to destroy already destroyed instance: %s"
msgstr ""

#: ../engine/compute/manager.py:675
#, python-format
msgid "Rebooting instance %s"
msgstr ""

#: ../engine/compute/manager.py:599
#, python-format
msgid ""
"trying to reboot a non-running instance: %(instance_id)s (state: %(state)s "
"expected: %(running)s)"
msgstr ""

#: ../engine/compute/manager.py:734
#, python-format
msgid "instance %s: snapshotting"
msgstr ""

#: ../engine/compute/manager.py:651
#, python-format
msgid ""
"trying to snapshot a non-running instance: %(instance_id)s (state: %(state)s "
"expected: %(running)s)"
msgstr ""

#: ../engine/compute/manager.py:332
#, python-format
msgid ""
"trying to reset the password on a non-running instance: %(instance_id)s "
"(state: %(instance_state)s expected: %(expected_state)s)"
msgstr ""

#: ../engine/compute/manager.py:335
#, python-format
msgid "instance %s: setting admin password"
msgstr ""

#: ../engine/compute/manager.py:772
#, python-format
msgid ""
"trying to inject a file into a non-running instance: %(instance_id)s (state: "
"%(instance_state)s expected: %(expected_state)s)"
msgstr ""

#: ../engine/compute/manager.py:362
#, python-format
msgid "instance %(nm)s: injecting file to %(plain_path)s"
msgstr ""

#: ../engine/compute/manager.py:902
#, python-format
msgid "instance %s: rescuing"
msgstr ""

#: ../engine/compute/manager.py:924
#, python-format
msgid "instance %s: unrescuing"
msgstr ""

#: ../engine/compute/manager.py:1204
#, python-format
msgid "instance %s: pausing"
msgstr ""

#: ../engine/compute/manager.py:1221
#, python-format
msgid "instance %s: unpausing"
msgstr ""

#: ../engine/compute/manager.py:1249
#, python-format
msgid "instance %s: retrieving diagnostics"
msgstr ""

#: ../engine/compute/manager.py:1257
#, python-format
msgid "instance %s: suspending"
msgstr ""

#: ../engine/compute/manager.py:1274
#, python-format
msgid "instance %s: resuming"
msgstr ""

#: ../engine/compute/manager.py:1292
#, python-format
msgid "instance %s: locking"
msgstr ""

#: ../engine/compute/manager.py:1300
#, python-format
msgid "instance %s: unlocking"
msgstr ""

#: ../engine/compute/manager.py:1307
#, python-format
msgid "instance %s: getting locked state"
msgstr ""

#: ../engine/compute/manager.py:1316
#, python-format
msgid "instance %s: reset network"
msgstr ""

#: ../engine/compute/manager.py:1336 ../engine/api/ec2/cloud.py:800
#, python-format
msgid "Get console output for instance %s"
msgstr ""

#: ../engine/compute/manager.py:1345
#, python-format
msgid "instance %s: getting ajax console"
msgstr ""

#: ../engine/compute/manager.py:1239
#, python-format
msgid ""
"instance %(instance_id)s: attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""

#. pylint: disable=W0702
#. NOTE(vish): The inline callback eats the exception info so we
#. log the traceback here and reraise the same
#. ecxception below.
#: ../engine/compute/manager.py:1265
#, python-format
msgid "instance %(instance_id)s: attach failed %(mountpoint)s, removing"
msgstr ""

#: ../engine/compute/manager.py:1436
#, python-format
msgid ""
"Detach volume %(volume_id)s from mountpoint %(mp)s on instance "
"%(instance_id)s"
msgstr ""

#: ../engine/compute/manager.py:1441
#, python-format
msgid "Detaching volume from unknown instance %s"
msgstr ""

#: ../engine/scheduler/simple.py:52
#, python-format
msgid "Host %s is not alive"
msgstr ""

#: ../engine/scheduler/simple.py:67
msgid "All hosts have too many cores"
msgstr ""

#: ../engine/scheduler/simple.py:94 ../engine/scheduler/vsa.py:223
#, python-format
msgid "Host %s not available"
msgstr ""

#: ../engine/scheduler/simple.py:119
msgid "All hosts have too many gigabytes"
msgstr ""

#: ../engine/scheduler/simple.py:136
msgid "All hosts have too many networks"
msgstr ""

#: ../engine/volume/manager.py:89
#, python-format
msgid "Re-exporting %s volumes"
msgstr ""

#: ../engine/volume/manager.py:94
#, python-format
msgid "volume %s: skipping export"
msgstr ""

#: ../engine/volume/manager.py:100
#, python-format
msgid "volume %s: creating"
msgstr ""

#: ../engine/volume/manager.py:112
#, python-format
msgid "volume %(vol_name)s: creating lv of size %(vol_size)sG"
msgstr ""

#: ../engine/volume/manager.py:124
#, python-format
msgid "volume %s: creating export"
msgstr ""

#: ../engine/volume/manager.py:138
#, python-format
msgid "volume %s: created successfully"
msgstr ""

#: ../engine/volume/manager.py:167
msgid "Volume is still attached"
msgstr ""

#: ../engine/volume/manager.py:169
msgid "Volume is not local to this node"
msgstr ""

#: ../engine/volume/manager.py:173
#, python-format
msgid "volume %s: removing export"
msgstr ""

#: ../engine/volume/manager.py:175
#, python-format
msgid "volume %s: deleting"
msgstr ""

#: ../engine/volume/manager.py:190
#, python-format
msgid "volume %s: deleted successfully"
msgstr ""

#: ../engine/virt/xenapi/fake.py:77 ../engine/virt/vmwareapi/fake.py:45
#, python-format
msgid "%(text)s: _db_content => %(content)s"
msgstr ""

#: ../engine/virt/xenapi/fake.py:495 ../engine/virt/xenapi/fake.py:594
#: ../engine/virt/xenapi/fake.py:612 ../engine/virt/xenapi/fake.py:675
msgid "Raising NotImplemented"
msgstr ""

#: ../engine/virt/xenapi/fake.py:497
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr ""

#: ../engine/virt/xenapi/fake.py:531
#, python-format
msgid "Calling %(localname)s %(impl)s"
msgstr ""

#: ../engine/virt/xenapi/fake.py:536
#, python-format
msgid "Calling getter %s"
msgstr ""

#: ../engine/virt/xenapi/fake.py:596
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""

#: ../engine/tests/test_cloud.py:256
msgid "Can't test instances without a real virtual env."
msgstr ""

#: ../engine/tests/test_cloud.py:268
#, python-format
msgid "Need to watch instance %s until it's running..."
msgstr ""

#: ../engine/virt/connection.py:78
msgid "Failed to open connection to the hypervisor"
msgstr ""

#: ../engine/network/linux_net.py:925
#, python-format
msgid "Starting VLAN inteface %s"
msgstr ""

#: ../engine/network/linux_net.py:954
#, python-format
msgid "Starting Bridge interface for %s"
msgstr ""

#. pylint: disable=W0703
#: ../engine/network/linux_net.py:654
#, python-format
msgid "Hupping dnsmasq threw %s"
msgstr ""

#: ../engine/network/linux_net.py:656
#, python-format
msgid "Pid %d is stale, relaunching dnsmasq"
msgstr ""

#. pylint: disable=W0703
#: ../engine/network/linux_net.py:716
#, python-format
msgid "killing radvd threw %s"
msgstr ""

#: ../engine/network/linux_net.py:718
#, python-format
msgid "Pid %d is stale, relaunching radvd"
msgstr ""

#. pylint: disable=W0703
#: ../engine/network/linux_net.py:763
#, python-format
msgid "Killing dnsmasq threw %s"
msgstr ""

#: ../engine/utils.py:66
#, python-format
msgid "Inner Exception: %s"
msgstr ""

#: ../engine/utils.py:59
#, python-format
msgid "Class %s cannot be found"
msgstr ""

#: ../engine/utils.py:127
#, python-format
msgid "Fetching %s"
msgstr ""

#: ../engine/utils.py:168
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: ../engine/utils.py:184 ../engine/utils.py:234
#, python-format
msgid "Result was %s"
msgstr ""

#: ../engine/utils.py:210
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: ../engine/utils.py:274
#, python-format
msgid "debug in callback: %s"
msgstr ""

#: ../engine/utils.py:279
#, python-format
msgid "Running %s"
msgstr ""

#: ../engine/utils.py:384
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: ../engine/utils.py:387
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: ../engine/utils.py:484
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: ../engine/utils.py:495
#, python-format
msgid "backend %s"
msgstr ""

#: ../engine/testing/fake/rabbit.py:50
#, python-format
msgid "(%(nm)s) publish (key: %(routing_key)s) %(message)s"
msgstr ""

#: ../engine/testing/fake/rabbit.py:54
#, python-format
msgid "Publishing to route %s"
msgstr ""

#: ../engine/testing/fake/rabbit.py:84
#, python-format
msgid "Declaring queue %s"
msgstr ""

#: ../engine/testing/fake/rabbit.py:90
#, python-format
msgid "Declaring exchange %s"
msgstr ""

#: ../engine/testing/fake/rabbit.py:96
#, python-format
msgid "Binding %(queue)s to %(exchange)s with key %(routing_key)s"
msgstr ""

#: ../engine/testing/fake/rabbit.py:133
#, python-format
msgid "Getting from %(queue)s: %(message)s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:192 ../engine/virt/hyperv.py:189
#, python-format
msgid "Created VM %s..."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:195
#, python-format
msgid "Created VM %(instance_name)s as %(vm_ref)s."
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:206
#, python-format
msgid "Creating VBD for VM %(vm_ref)s, VDI %(vdi_ref)s ... "
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:209
#, python-format
msgid "Created VBD %(vbd_ref)s for VM %(vm_ref)s, VDI %(vdi_ref)s."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:246
#, python-format
msgid "VBD not found in instance %s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:257
#, python-format
msgid "Unable to unplug VBD %s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:268
#, python-format
msgid "Unable to destroy VBD %s"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:1451
#, python-format
msgid "Creating VIF for VM %(vm_ref)s, network %(network_ref)s."
msgstr ""

#: ../engine/virt/xenapi/vmops.py:1454
#, python-format
msgid "Created VIF %(vif_ref)s for VM %(vm_ref)s, network %(network_ref)s."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:295
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(name_label)s, %(virtual_size)s, %(read_only)s) on "
"%(sr_ref)s."
msgstr ""

#. TODO(sirp): Add quiesce and VSS locking support when Windows support
#. is added
#: ../engine/virt/xenapi/vm_utils.py:324
#, python-format
msgid "Snapshotting VM %(vm_ref)s with label '%(label)s'..."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:338
#, python-format
msgid "Created snapshot %(template_vm_ref)s from VM %(vm_ref)s."
msgstr ""

#. NOTE(sirp): Currently we only support uploading images as VHD, there
#. is no RAW equivalent (yet)
#: ../engine/virt/xenapi/vm_utils.py:368
#, python-format
msgid "Asking xapi to upload %(vdi_uuids)s as ID %(image_id)s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:327
#, python-format
msgid "Size for image %(image)s:%(virtual_size)d"
msgstr ""

#. TODO(sirp): This should eventually be the URI for the Tank image
#: ../engine/virt/xenapi/vm_utils.py:1157
#, python-format
msgid "Tank image %s"
msgstr ""

#. We need to invoke a plugin for copying the
#. content of the VDI into the proper path.
#: ../engine/virt/xenapi/vm_utils.py:673
#, python-format
msgid "Copying VDI %s to /boot/guest on dom0"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:683
#, python-format
msgid "Kernel/Ramdisk VDI %s destroyed"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:361
#, python-format
msgid "Asking xapi to fetch %(url)s as %(access)s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:761
#, python-format
msgid "Looking up vdi %s for PV kernel"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:397
#, python-format
msgid "PV Kernel in VDI:%s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1295
#, python-format
msgid "Running pygrub against %s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1302
#, python-format
msgid "Found Xen kernel %s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1304
msgid "No Xen kernel found.  Booting HVM."
msgstr ""

#: ../engine/virt/hyperv.py:450
#, python-format
msgid "duplicate name found: %s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:821
#, python-format
msgid "VDI %s is still available"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:859
#, python-format
msgid "(VM_UTILS) xenserver vm state -> |%s|"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:861
#, python-format
msgid "(VM_UTILS) xenapi power_state -> |%s|"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1102
#, python-format
msgid "VHD %(vdi_uuid)s has parent %(parent_ref)s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:917
#, python-format
msgid "Re-scanning SR %s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1153
#, python-format
msgid ""
"VHD coalesce attempts exceeded (%(counter)d > %(max_attempts)d), giving up..."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1160
#, python-format
msgid ""
"Parent %(parent_uuid)s doesn't match original parent "
"%(original_parent_uuid)s, waiting for coalesce..."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:911
#, python-format
msgid "No VDIs found for VM %s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:594
#, python-format
msgid "Unexpected number of VDIs (%(num_vdis)s) found for VM %(vm_ref)s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1222
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:188
#, python-format
msgid "Creating VBD for VDI %s ... "
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1224
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:190
#, python-format
msgid "Creating VBD for VDI %s done."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1226
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:192
#, python-format
msgid "Plugging VBD %s ... "
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1229
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:194
#, python-format
msgid "Plugging VBD %s done."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:661
#, python-format
msgid "VBD %(vbd)s plugged as %(orig_dev)s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:664
#, python-format
msgid "VBD %(vbd)s plugged into wrong dev, remapping to %(dev)s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1243
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:197
#, python-format
msgid "Destroying VBD for VDI %s ... "
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1247
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:200
#, python-format
msgid "Destroying VBD for VDI %s done."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1259
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:211
msgid "VBD.unplug successful first time."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1264
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:216
msgid "VBD.unplug rejected: retrying..."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1269
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:220
msgid "VBD.unplug successful eventually."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1272
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:223
#, python-format
msgid "Ignoring XenAPI.Failure in VBD.unplug: %s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1281
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:66
#, python-format
msgid "Ignoring XenAPI.Failure %s"
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1140
#, python-format
msgid ""
"Writing partition table %(primary_first)d %(primary_last)d to %(dest)s..."
msgstr ""

#: ../engine/virt/xenapi/vm_utils.py:1362
#, python-format
msgid "Writing partition table %s done."
msgstr ""

#: ../engine/tests/rpc/common.py:142
#, python-format
msgid "Nested received %(queue)s, %(value)s"
msgstr ""

#: ../engine/tests/rpc/common.py:150
#, python-format
msgid "Nested return %s"
msgstr ""

#: ../engine/tests/rpc/common.py:176 ../engine/tests/rpc/common.py:182
#, python-format
msgid "Received %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:50
msgid "Use of empty request context is deprecated"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:133
#, python-format
msgid "No service for id %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:251
#, python-format
msgid "No service for %(host)s, %(binary)s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:592
msgid "No fixed ips defined"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:608
#, python-format
msgid "No floating ip for address %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:629
#, python-format
msgid "No address for instance %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:961
#, python-format
msgid "no keypair for user %(user_id)s, name %(name)s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1076 ../engine/db/sqlalchemy/api.py:1156
#, python-format
msgid "No network for id %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1086
msgid "No networks defined"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1115
#, python-format
msgid "No network for bridge %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1129 ../engine/db/sqlalchemy/api.py:1142
#, python-format
msgid "No network for instance %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1277
#, python-format
msgid "Token %s does not exist"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1302
#, python-format
msgid "No quota for project_id %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1455 ../engine/db/sqlalchemy/api.py:1501
#: ../engine/api/ec2/__init__.py:323
#, python-format
msgid "Volume %s not found"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1514
#, python-format
msgid "No export device found for volume %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1527
#, python-format
msgid "No target id found for volume %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1572
#, python-format
msgid "No security group with id %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1589
#, python-format
msgid "No security group named %(group_name)s for project: %(project_id)s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1682
#, python-format
msgid "No secuity group rule with id %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1756
#, python-format
msgid "No user for id %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1772
#, python-format
msgid "No user for access key %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1834
#, python-format
msgid "No project with id %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1979
#, python-format
msgid "No console pool with id %(pool_id)s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:1996
#, python-format
msgid ""
"No console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:2035
#, python-format
msgid "No console for instance %(instance_id)s in pool %(pool_id)s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:2057
#, python-format
msgid "on instance %s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:2058
#, python-format
msgid "No console with id %(console_id)s %(idesc)s"
msgstr ""

#: ../engine/db/sqlalchemy/api.py:2078 ../engine/db/sqlalchemy/api.py:2097
#, python-format
msgid "No zone with id %(zone_id)s"
msgstr ""

#: ../engine/compute/manager.py:192
#, python-format
msgid "Checking state of %s"
msgstr ""

#: ../engine/virt/libvirt_conn.py:165
#, python-format
msgid "Current state of %(name)s was %(state)s."
msgstr ""

#: ../engine/virt/libvirt/connection.py:226
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: ../engine/virt/libvirt/connection.py:240
msgid "Connection to libvirt broke"
msgstr ""

#: ../engine/virt/libvirt/connection.py:390
#, python-format
msgid "instance %(instance_name)s: deleting instance files %(target)s"
msgstr ""

#: ../engine/virt/libvirt_conn.py:283
#, python-format
msgid "Invalid device path %s"
msgstr ""

#: ../engine/virt/libvirt_conn.py:313
#, python-format
msgid "No disk at %s"
msgstr ""

#: ../engine/virt/libvirt_conn.py:320
msgid "Instance snapshotting is not supported for libvirtat this time"
msgstr ""

#: ../engine/virt/libvirt_conn.py:336
#, python-format
msgid "instance %s: rebooted"
msgstr ""

#: ../engine/virt/libvirt_conn.py:339
#, python-format
msgid "_wait_for_reboot failed: %s"
msgstr ""

#: ../engine/virt/libvirt_conn.py:382
#, python-format
msgid "instance %s: rescued"
msgstr ""

#: ../engine/virt/libvirt_conn.py:385
#, python-format
msgid "_wait_for_rescue failed: %s"
msgstr ""

#: ../engine/virt/libvirt/connection.py:665
#, python-format
msgid "instance %s: is running"
msgstr ""

#: ../engine/virt/libvirt_conn.py:422
#, python-format
msgid "instance %s: booted"
msgstr ""

#: ../engine/virt/libvirt_conn.py:425 ../engine/virt/xenapi/vmops.py:186
#, python-format
msgid "instance %s: failed to boot"
msgstr ""

#: ../engine/virt/libvirt/connection.py:688
#, python-format
msgid "virsh said: %r"
msgstr ""

#: ../engine/virt/libvirt/connection.py:692
msgid "cool, it's a device"
msgstr ""

#: ../engine/virt/libvirt/connection.py:703
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: ../engine/virt/libvirt/connection.py:745
#, python-format
msgid "Contents of file %(fpath)s: %(contents)r"
msgstr ""

#: ../engine/virt/libvirt/utils.py:218
msgid "Unable to find an open port"
msgstr ""

#: ../engine/virt/libvirt/connection.py:849
#, python-format
msgid "instance %s: Creating image"
msgstr ""

#: ../engine/virt/libvirt_conn.py:646
#, python-format
msgid "instance %(inst_name)s: injecting key into image %(img_id)s"
msgstr ""

#: ../engine/virt/libvirt_conn.py:649
#, python-format
msgid "instance %(inst_name)s: injecting net into image %(img_id)s"
msgstr ""

#. This could be a windows image, or a vmdk format disk
#: ../engine/virt/libvirt/connection.py:1039
#, python-format
msgid ""
"instance %(inst_name)s: ignoring error injecting data into image %(img_id)s "
"(%(e)s)"
msgstr ""

#. TODO(termie): cache?
#: ../engine/virt/libvirt/connection.py:1178
#, python-format
msgid "instance %s: starting toXML method"
msgstr ""

#: ../engine/virt/libvirt/connection.py:1182
#, python-format
msgid "instance %s: finished toXML method"
msgstr ""

#: ../engine/virt/libvirt/connection.py:1330
msgid "diagnostics are not supported for libvirt"
msgstr ""

#: ../engine/virt/libvirt/firewall.py:540
#, python-format
msgid "Attempted to unfilter instance %s which is not filtered"
msgstr ""

#: ../engine/api/metadata/handler.py:250 ../engine/api/metadata/handler.py:257
#, python-format
msgid "Failed to get metadata for ip: %s"
msgstr ""

#: ../engine/auth/fakeldap.py:33
msgid "Attempted to instantiate singleton"
msgstr ""

#: ../engine/network/api.py:39
#, python-format
msgid "Quota exceeeded for %s, tried to allocate address"
msgstr ""

#: ../engine/network/manager.py:296
msgid "Address quota exceeded. You cannot allocate any more addresses"
msgstr ""

#: ../engine/tests/test_volume.py:190
#, python-format
msgid "Target %s allocated"
msgstr ""

#: ../engine/virt/images.py:70
#, python-format
msgid "Finished retreving %(url)s -- placed in %(path)s"
msgstr ""

#: ../engine/scheduler/driver.py:165
msgid "Must implement a fallback schedule"
msgstr ""

#: ../engine/console/manager.py:71 ../engine/console/vmrc_manager.py:64
msgid "Adding console"
msgstr ""

#: ../engine/console/manager.py:91
#, python-format
msgid "Tried to remove non-existant console %(console_id)s."
msgstr ""

#: ../engine/api/direct.py:219
msgid "not available"
msgstr ""

#: ../engine/api/ec2/cloud.py:62
#, python-format
msgid "The key_pair %s already exists"
msgstr ""

#. TODO(vish): Do this with M2Crypto instead
#: ../engine/api/ec2/cloud.py:227
#, python-format
msgid "Generating root CA: %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:385
#, python-format
msgid "Create key pair %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:414
#, python-format
msgid "Delete key pair %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:386
#, python-format
msgid "%s is not a valid ipProtocol"
msgstr ""

#: ../engine/api/ec2/cloud.py:390
msgid "Invalid port range"
msgstr ""

#: ../engine/api/x7/v2/contrib/security_groups.py:348
#, python-format
msgid "Revoke security group ingress %s"
msgstr ""

#: ../engine/api/x7/v2/contrib/security_groups.py:210
msgid "Not enough parameters to build a valid rule."
msgstr ""

#: ../engine/api/ec2/cloud.py:673 ../engine/api/ec2/cloud.py:729
msgid "No rule for the specified parameters."
msgstr ""

#: ../engine/api/x7/v2/contrib/security_groups.py:195
#, python-format
msgid "Authorize security group ingress %s"
msgstr ""

#: ../engine/api/x7/v2/contrib/security_groups.py:217
#, python-format
msgid "This rule already exists in group %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:765
#: ../engine/api/x7/v2/contrib/security_groups.py:137
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:768
#, python-format
msgid "group %s already exists"
msgstr ""

#: ../engine/api/ec2/cloud.py:795
#: ../engine/api/x7/v2/contrib/security_groups.py:97
#, python-format
msgid "Delete security group %s"
msgstr ""

#: ../engine/api/x7/v2/contrib/volumes.py:157
#: ../engine/api/ec2/cloud.py:887
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: ../engine/api/ec2/cloud.py:922
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: ../engine/api/x7/v2/contrib/volumes.py:302
#: ../engine/api/ec2/cloud.py:936
#, python-format
msgid "Detach volume %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:1221
msgid "Allocate address"
msgstr ""

#: ../engine/api/ec2/cloud.py:1233
#, python-format
msgid "Release address %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:1238
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: ../engine/api/ec2/cloud.py:1248
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:1296
msgid "Going to start terminating instances"
msgstr ""

#: ../engine/api/ec2/cloud.py:1305
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: ../engine/api/ec2/cloud.py:1445
#, python-format
msgid "De-registering image %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:1472
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: ../engine/api/ec2/cloud.py:963 ../engine/api/ec2/cloud.py:1024
#: ../engine/api/ec2/cloud.py:1500 ../engine/api/ec2/cloud.py:1515
#, python-format
msgid "attribute not supported: %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:890
#, python-format
msgid "invalid id: %s"
msgstr ""

#: ../engine/api/ec2/cloud.py:1518
msgid "user or group not specified"
msgstr ""

#: ../engine/api/ec2/cloud.py:1520
msgid "only group \"all\" is supported"
msgstr ""

#: ../engine/api/ec2/cloud.py:1522
msgid "operation_type must be add or remove"
msgstr ""

#: ../engine/api/ec2/cloud.py:1523
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: ../bin/engine-api.py:52
#, python-format
msgid "Using paste.deploy config at: %s"
msgstr ""

#: ../bin/engine-api.py:57
#, python-format
msgid "No paste configuration for app: %s"
msgstr ""

#: ../bin/engine-api.py:59
#, python-format
msgid ""
"App Config: %(api)s\n"
"%(config)r"
msgstr ""

#: ../bin/engine-api.py:64
#, python-format
msgid "Running %s API"
msgstr ""

#: ../bin/engine-api.py:69
#, python-format
msgid "No known API applications configured in %s."
msgstr ""

#: ../bin/engine-api.py:83
#, python-format
msgid "Starting engine-api node (version %s)"
msgstr ""

#: ../bin/engine-api.py:89
#, python-format
msgid "No paste configuration found for: %s"
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:84
#, python-format
msgid "Argument %(key)s value %(value)s is too short."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:89
#, python-format
msgid "Argument %(key)s value %(value)s contains invalid characters."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:94
#, python-format
msgid "Argument %(key)s value %(value)s starts with a hyphen."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:102
#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:130
#, python-format
msgid "Argument %s is required."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:117
#, python-format
msgid ""
"Argument %(key)s may not take value %(value)s. Valid values are ['true', "
"'false']."
msgstr ""

#: ../plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_engine.py:163
#, python-format
msgid ""
"Created VDI %(vdi_ref)s (%(label)s, %(size)s, %(read_only)s) on %(sr_ref)s."
msgstr ""

#: ../engine/virt/xenapi/vmops.py:67
#, python-format
msgid "Attempted to create non-unique name %s"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:73
#, python-format
msgid "instance %(name)s: not enough free memory"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:388
#, python-format
msgid "Starting VM %s..."
msgstr ""

#: ../engine/virt/xenapi/vmops.py:391
#, python-format
msgid "Spawning VM %(instance_name)s created %(vm_ref)s."
msgstr ""

#: ../engine/virt/xenapi/vmops.py:162
#, python-format
msgid "Invalid value for onset_files: '%s'"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:437
#, python-format
msgid "Injecting file path: '%s'"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:467
#, python-format
msgid "Instance %s: booted"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:232
#, python-format
msgid "Instance not present %s"
msgstr ""

#. TODO(sirp): Add quiesce and VSS locking support when Windows support
#. is added
#: ../engine/virt/xenapi/vmops.py:612
#, python-format
msgid "Starting snapshot for VM %s"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:621
#, python-format
msgid "Unable to Snapshot %(vm_ref)s: %(exc)s"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:606
#, python-format
msgid "Finished snapshot and upload for VM %s"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:356
#, python-format
msgid "VM %(vm)s already halted, skipping shutdown..."
msgstr ""

#: ../engine/virt/xenapi/vmops.py:389
msgid "Removing kernel/ramdisk files"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:1086
msgid "kernel/ramdisk files removed"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:561
#, python-format
msgid ""
"TIMEOUT: The call to %(method)s timed out. VM id=%(instance_id)s; "
"args=%(strargs)s"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:564
#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. VM "
"id=%(instance_id)s; args=%(strargs)s"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:569
#, python-format
msgid ""
"The call to %(method)s returned an error: %(e)s. VM id=%(instance_id)s; "
"args=%(strargs)s"
msgstr ""

#: ../engine/virt/xenapi/vmops.py:1761
#, python-format
msgid "OpenSSL error: %s"
msgstr ""

#: ../engine/tests/test_compute.py:204 ../engine/tests/test_compute.py:1051
#, python-format
msgid "Running instances: %s"
msgstr ""

#: ../engine/tests/test_compute.py:210
#, python-format
msgid "After terminating instances: %s"
msgstr ""

#: ../engine/cloudpipe/pipelib.py:45
msgid "Template for script to run on cloudpipe instance boot"
msgstr ""

#: ../engine/cloudpipe/pipelib.py:48
msgid "Network to push into openvpn config"
msgstr ""

#: ../engine/cloudpipe/pipelib.py:51
msgid "Netmask to push into openvpn config"
msgstr ""

#: ../engine/cloudpipe/pipelib.py:96
#, python-format
msgid "Launching VPN for %s"
msgstr ""

#: ../engine/db/sqlalchemy/migration.py:36
msgid "python-migrate is not installed. Exiting."
msgstr ""

#: ../engine/image/s3.py:99
#, python-format
msgid "Image %s could not be found"
msgstr ""

#: ../engine/api/ec2/__init__.py:134
msgid "Too many failed authentications."
msgstr ""

#: ../engine/api/ec2/__init__.py:144
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and "
"will be locked out for %(lock_mins)d minutes."
msgstr ""

#: ../engine/api/ec2/__init__.py:204
#, python-format
msgid "Authentication Failure: %s"
msgstr ""

#: ../engine/api/ec2/__init__.py:220
#, python-format
msgid "Authenticated Request For %(uname)s:%(pname)s)"
msgstr ""

#: ../engine/api/ec2/__init__.py:251
#, python-format
msgid "action: %s"
msgstr ""

#: ../engine/api/ec2/__init__.py:253
#, python-format
msgid "arg: %(key)s\t\tval: %(value)s"
msgstr ""

#: ../engine/api/ec2/__init__.py:328
#, python-format
msgid ""
"Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: ../engine/api/ec2/__init__.py:359
#, python-format
msgid "InstanceNotFound raised: %s"
msgstr ""

#: ../engine/api/ec2/__init__.py:365
#, python-format
msgid "VolumeNotFound raised: %s"
msgstr ""

#: ../engine/api/ec2/__init__.py:377
#, python-format
msgid "NotFound raised: %s"
msgstr ""

#: ../engine/api/ec2/__init__.py:380
#, python-format
msgid "ApiError raised: %s"
msgstr ""

#: ../engine/api/ec2/__init__.py:409
#, python-format
msgid "Unexpected error raised: %s"
msgstr ""

#: ../engine/api/metadata/handler.py:252 ../engine/api/ec2/__init__.py:414
msgid "An unknown error has occurred. Please try your request again."
msgstr ""

#: ../engine/auth/dbdriver.py:84
#, python-format
msgid "User %s already exists"
msgstr ""

#: ../engine/auth/dbdriver.py:106 ../engine/auth/ldapdriver.py:232
#, python-format
msgid "Project can't be created because manager %s doesn't exist"
msgstr ""

#: ../engine/auth/dbdriver.py:122 ../engine/auth/ldapdriver.py:243
#, python-format
msgid "Project can't be created because user %s doesn't exist"
msgstr ""

#: ../engine/auth/dbdriver.py:135 ../engine/auth/ldapdriver.py:229
#, python-format
msgid "Project can't be created because project %s already exists"
msgstr ""

#: ../engine/auth/dbdriver.py:157 ../engine/auth/ldapdriver.py:268
#, python-format
msgid "Project can't be modified because manager %s doesn't exist"
msgstr ""

#: ../engine/auth/dbdriver.py:245
#, python-format
msgid "User \"%s\" not found"
msgstr ""

#: ../engine/auth/dbdriver.py:248
#, python-format
msgid "Project \"%s\" not found"
msgstr ""

#: ../engine/virt/xenapi_conn.py:159
msgid ""
"Must specify xenapi_connection_url, xenapi_connection_username (optionally), "
"and xenapi_connection_password to use connection_type=xenapi"
msgstr ""

#: ../engine/virt/xenapi_conn.py:536
#, python-format
msgid "Task [%(name)s] %(task)s status: success    %(result)s"
msgstr ""

#: ../engine/virt/xenapi_conn.py:545
#, python-format
msgid "Task [%(name)s] %(task)s status: %(status)s    %(error_info)s"
msgstr ""

#: ../engine/virt/xenapi_conn.py:571 ../engine/virt/xenapi_conn.py:584
#, python-format
msgid "Got exception: %s"
msgstr ""

#: ../engine/volume/driver.py:359
#, python-format
msgid "Could not find iSCSI export  for volume %s"
msgstr ""

#: ../engine/api/ec2/apirequest.py:73
#, python-format
msgid ""
"Unsupported API request: controller = %(controller)s, action = %(action)s"
msgstr ""

#: ../engine/api/x7/v2/__init__.py:63
#, python-format
msgid "Caught error: %s"
msgstr ""

#: ../engine/api/x7/v2/__init__.py:113
msgid "Including admin operations in API."
msgstr ""

#: ../engine/console/xvp.py:93
msgid "Rebuilding xvp conf"
msgstr ""

#: ../engine/console/xvp.py:111
#, python-format
msgid "Re-wrote %s"
msgstr ""

#: ../engine/console/xvp.py:116
msgid "Stopping xvp"
msgstr ""

#: ../engine/console/xvp.py:129
msgid "Starting xvp"
msgstr ""

#: ../engine/console/xvp.py:136
#, python-format
msgid "Error starting xvp: %s"
msgstr ""

#: ../engine/console/xvp.py:139
msgid "Restarting xvp"
msgstr ""

#: ../engine/console/xvp.py:141
msgid "xvp not running..."
msgstr ""

#: ../bin/engine-manage.py:272
msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using engine-manage sync db before running this "
"command."
msgstr ""

#: ../bin/engine-manage.py:426
msgid ""
"No more networks available. If this is a new installation, you need\n"
"to call something like this:\n"
"\n"
"    engine-manage network create 10.0.0.0/8 10 64\n"
"\n"
msgstr ""

#: ../bin/engine-manage.py:609
msgid ""
"The above error may show that the certificate db has not been created.\n"
"Please create a database by running a engine-api server on this host."
msgstr ""

#: ../bin/engine-manage.py:633
msgid "network"
msgstr ""

#: ../bin/engine-manage.py:634
msgid "IP address"
msgstr ""

#: ../bin/engine-manage.py:635
msgid "MAC address"
msgstr ""

#: ../bin/engine-manage.py:636
msgid "hostname"
msgstr ""

#: ../bin/engine-manage.py:637 ../bin/engine-manage.py:1136
#: ../bin/engine-manage.py:1252 ../bin/engine-manage.py:1284
msgid "host"
msgstr ""

#: ../bin/engine-manage.py:537
msgid "netmask"
msgstr ""

#: ../bin/engine-manage.py:832 ../engine/tests/test_engine_manage.py:183
msgid "start address"
msgstr ""

#: ../engine/virt/disk.py:124
#, python-format
msgid "Failed to load partition: %s"
msgstr ""

#: ../engine/virt/disk.py:148 ../engine/virt/disk.py:180
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: ../engine/virt/disk.py:217
#, python-format
msgid "nbd device %s did not show up"
msgstr ""

#: ../engine/virt/disk.py:222
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#: ../engine/virt/disk.py:246
msgid "No free nbd devices"
msgstr ""

#: ../doc/ext/engine_todo.py:46
#, python-format
msgid "%(filename)s, line %(line_info)d"
msgstr ""

#. FIXME(chiradeep): implement this
#: ../engine/virt/hyperv.py:119
msgid "In init host"
msgstr ""

#: ../engine/virt/hyperv.py:131
#, python-format
msgid "Attempt to create duplicate vm %s"
msgstr ""

#: ../engine/virt/hyperv.py:166
#, python-format
msgid "Starting VM %s "
msgstr ""

#: ../engine/virt/hyperv.py:168
#, python-format
msgid "Started VM %s "
msgstr ""

#: ../engine/virt/hyperv.py:170
#, python-format
msgid "spawn vm failed: %s"
msgstr ""

#: ../engine/virt/hyperv.py:187
#, python-format
msgid "Failed to create VM %s"
msgstr ""

#: ../engine/virt/hyperv.py:206
#, python-format
msgid "Set memory for vm %s..."
msgstr ""

#: ../engine/virt/hyperv.py:216
#, python-format
msgid "Set vcpus for vm %s..."
msgstr ""

#: ../engine/virt/hyperv.py:220
#, python-format
msgid "Creating disk for %(vm_name)s by attaching disk file %(vhdfile)s"
msgstr ""

#: ../engine/virt/hyperv.py:245
#, python-format
msgid "Failed to add diskdrive to VM %s"
msgstr ""

#: ../engine/virt/hyperv.py:248
#, python-format
msgid "New disk drive path is %s"
msgstr ""

#: ../engine/virt/hyperv.py:265
#, python-format
msgid "Failed to add vhd file to VM %s"
msgstr ""

#: ../engine/virt/hyperv.py:267
#, python-format
msgid "Created disk for %s"
msgstr ""

#: ../engine/virt/hyperv.py:271
#, python-format
msgid "Creating nic for %s "
msgstr ""

#: ../engine/virt/hyperv.py:290
msgid "Failed creating a port on the external vswitch"
msgstr ""

#: ../engine/virt/hyperv.py:291
#, python-format
msgid "Failed creating port for %s"
msgstr ""

#: ../engine/virt/hyperv.py:294
#, python-format
msgid "Created switch port %(vm_name)s on switch %(ext_path)s"
msgstr ""

#: ../engine/virt/hyperv.py:304
#, python-format
msgid "Failed to add nic to VM %s"
msgstr ""

#: ../engine/virt/hyperv.py:306
#, python-format
msgid "Created nic for %s "
msgstr ""

#: ../engine/virt/hyperv.py:339
#, python-format
msgid "WMI job failed: %s"
msgstr ""

#: ../engine/virt/hyperv.py:343
#, python-format
msgid "WMI job succeeded: %(desc)s, Elapsed=%(elap)s "
msgstr ""

#: ../engine/virt/hyperv.py:380
#, python-format
msgid "Got request to destroy vm %s"
msgstr ""

#: ../engine/virt/hyperv.py:405
#, python-format
msgid "Failed to destroy vm %s"
msgstr ""

#: ../engine/virt/hyperv.py:412
#, python-format
msgid "Del: disk %(vhdfile)s vm %(instance_name)s"
msgstr ""

#: ../engine/virt/hyperv.py:433
#, python-format
msgid ""
"Got Info for vm %(instance_id)s: state=%(state)s, mem=%(memusage)s, "
"num_cpu=%(numprocs)s, cpu_time=%(uptime)s"
msgstr ""

#: ../engine/virt/hyperv.py:470
#, python-format
msgid "Successfully changed vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: ../engine/virt/hyperv.py:473
#, python-format
msgid "Failed to change vm state of %(vm_name)s to %(req_state)s"
msgstr ""

#: ../engine/compute/api.py:71
#, python-format
msgid "Instance %d was not found in get_network_topic"
msgstr ""

#: ../engine/compute/api.py:77
#, python-format
msgid "Instance %d has no host"
msgstr ""

#: ../engine/compute/api.py:97
#, python-format
msgid "Quota exceeeded for %(pid)s, tried to run %(min_count)s instances"
msgstr ""

#: ../engine/compute/api.py:199
#, python-format
msgid ""
"Instance quota exceeded. You can only run %s more instances of this type."
msgstr ""

#: ../engine/compute/api.py:248
msgid "Creating a raw instance"
msgstr ""

#: ../engine/compute/api.py:303
#, python-format
msgid "Going to run %s instances..."
msgstr ""

#: ../engine/compute/api.py:187
#, python-format
msgid "Casting to scheduler for %(pid)s/%(uid)s's instance %(instance_id)s"
msgstr ""

#: ../engine/compute/api.py:812
#, python-format
msgid "Going to try to terminate %s"
msgstr ""

#: ../engine/compute/api.py:296
#, python-format
msgid "Instance %d was not found during terminate"
msgstr ""

#: ../engine/compute/api.py:301
#, python-format
msgid "Instance %d is already being terminated"
msgstr ""

#: ../engine/compute/api.py:1511
#, python-format
msgid "Invalid device specified: %s. Example device: /dev/vdb"
msgstr ""

#: ../engine/compute/api.py:1526
msgid "Volume isn't attached to anything!"
msgstr ""

#: ../engine/rpc.py:98
#, python-format
msgid ""
"AMQP server on %(fl_host)s:%(fl_port)d is unreachable. Trying again in "
"%(fl_intv)d seconds."
msgstr ""

#: ../engine/rpc.py:103
#, python-format
msgid "Unable to connect to AMQP server after %d tries. Shutting down."
msgstr ""

#: ../engine/rpc/impl_carrot.py:220
msgid "Reconnected to queue"
msgstr ""

#: ../engine/rpc.py:129
msgid "Failed to fetch message from queue"
msgstr ""

#: ../engine/rpc/impl_carrot.py:235
#, python-format
msgid "Initing the Adapter Consumer for %s"
msgstr ""

#: ../engine/rpc/impl_kombu.py:600 ../engine/rpc/impl_carrot.py:255
#, python-format
msgid "received %s"
msgstr ""

#. NOTE(vish): we may not want to ack here, but that means that bad
#. messages stay in the queue indefinitely, so for now
#. we just log the message and send an error string
#. back to the caller
#: ../engine/rpc/impl_kombu.py:605 ../engine/rpc/impl_carrot.py:268
#, python-format
msgid "no method for message: %s"
msgstr ""

#: ../engine/rpc/impl_kombu.py:606 ../engine/rpc/impl_carrot.py:270
#, python-format
msgid "No method for message: %s"
msgstr ""

#: ../engine/rpc/impl_kombu.py:779 ../engine/rpc/impl_carrot.py:453
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: ../engine/rpc/impl_kombu.py:646 ../engine/rpc/impl_carrot.py:486
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: ../engine/rpc.py:313
msgid "Making asynchronous call..."
msgstr ""

#: ../engine/rpc/impl_kombu.py:733 ../engine/rpc/impl_carrot.py:522
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: ../engine/rpc.py:354
msgid "Making asynchronous cast..."
msgstr ""

#: ../engine/rpc/impl_carrot.py:621
#, python-format
msgid "response %s"
msgstr ""

#: ../engine/rpc/impl_carrot.py:630
#, python-format
msgid "topic is %s"
msgstr ""

#: ../engine/rpc/impl_carrot.py:631
#, python-format
msgid "message %s"
msgstr ""

#: ../engine/volume/driver.py:79
#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr ""

#: ../engine/volume/driver.py:89
#, python-format
msgid "volume group %s doesn't exist"
msgstr ""

#: ../engine/volume/driver.py:342
#, python-format
msgid "FAKE AOE: %s"
msgstr ""

#: ../engine/volume/driver.py:251 ../engine/volume/driver.py:842
msgid "Skipping ensure_export. No iscsi_target "
msgstr ""

#: ../engine/volume/driver.py:295 ../engine/volume/driver.py:304
#: ../engine/volume/driver.py:886
msgid "Skipping remove_export. No iscsi_target "
msgstr ""

#: ../engine/volume/driver.py:463
#, python-format
msgid "FAKE ISCSI: %s"
msgstr ""

#: ../engine/volume/driver.py:475
#, python-format
msgid "rbd has no pool %s"
msgstr ""

#: ../engine/volume/driver.py:545
#, python-format
msgid "Sheepdog is not working: %s"
msgstr ""

#: ../engine/volume/driver.py:547
msgid "Sheepdog is not working"
msgstr ""

#: ../engine/wsgi.py:68
#, python-format
msgid "Starting %(arg0)s on %(host)s:%(port)s"
msgstr ""

#: ../engine/wsgi.py:208
msgid "You must implement __call__"
msgstr ""

#: ../bin/engine-dhcpbridge.py:58
msgid "leasing ip"
msgstr ""

#: ../bin/engine-dhcpbridge.py:73
msgid "Adopted old lease or got a change of mac/hostname"
msgstr ""

#: ../bin/engine-dhcpbridge.py:78
msgid "releasing ip"
msgstr ""

#: ../bin/engine-dhcpbridge.py:123
#, python-format
msgid ""
"Called %(action)s for mac %(mac)s with ip %(ip)s and hostname %(hostname)s "
"on interface %(interface)s"
msgstr ""

#: ../engine/virt/fake.py:239
#, python-format
msgid "Instance %s Not Found"
msgstr ""

#: ../engine/network/manager.py:386
#, python-format
msgid "Dissassociated %s stale fixed ip(s)"
msgstr ""

#: ../engine/network/manager.py:523
msgid "setting network host"
msgstr ""

#: ../engine/network/manager.py:212
#, python-format
msgid "Leasing IP %s"
msgstr ""

#: ../engine/network/manager.py:216
#, python-format
msgid "IP %s leased that isn't associated"
msgstr ""

#: ../engine/network/manager.py:220
#, python-format
msgid "IP %(address)s leased to bad mac %(inst_addr)s vs %(mac)s"
msgstr ""

#: ../engine/network/manager.py:228
#, python-format
msgid "IP %s leased that was already deallocated"
msgstr ""

#: ../engine/network/manager.py:233
#, python-format
msgid "Releasing IP %s"
msgstr ""

#: ../engine/network/manager.py:237
#, python-format
msgid "IP %s released that isn't associated"
msgstr ""

#: ../engine/network/manager.py:241
#, python-format
msgid "IP %(address)s released from bad mac %(inst_addr)s vs %(mac)s"
msgstr ""

#: ../engine/network/manager.py:870
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: ../engine/network/manager.py:1278
msgid ""
"The sum between the number of networks and the vlan start cannot be greater "
"than 4094"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:157
#, python-format
msgid "Introducing %s..."
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:103
#: ../engine/virt/xenapi/volume_utils.py:170
#: ../engine/virt/xenapi/volumeops.py:157
#, python-format
msgid "Introduced %(label)s as %(sr_ref)s."
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:76
#: ../engine/virt/xenapi/volume_utils.py:174
msgid "Unable to create Storage Repository"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:186
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:96
#, python-format
msgid "Forgetting SR %s ... "
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:228
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:234
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:111
#, python-format
msgid "Forgetting SR %s done."
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:113
#, python-format
msgid "Ignoring exception %(exc)s when forgetting SR %(sr_ref)s"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:249
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:257
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:279
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:175
#, python-format
msgid "Unable to obtain target information %(device_path)s, %(mountpoint)s"
msgstr ""

#: ../engine/virt/xenapi/volume_utils.py:356
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: ../engine/image/s3.py:365
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr ""

#: ../engine/image/s3.py:374
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr ""

#: ../engine/image/s3.py:385
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr ""

#: ../engine/objectstore/handler.py:106
#, python-format
msgid "Unknown S3 value type %r"
msgstr ""

#: ../engine/objectstore/handler.py:137
msgid "Authenticated request"
msgstr ""

#: ../engine/objectstore/handler.py:182
msgid "List of buckets requested"
msgstr ""

#: ../engine/objectstore/handler.py:209
#, python-format
msgid "List keys for bucket %s"
msgstr ""

#: ../engine/objectstore/handler.py:217
#, python-format
msgid "Unauthorized attempt to access bucket %s"
msgstr ""

#: ../engine/objectstore/handler.py:235
#, python-format
msgid "Creating bucket %s"
msgstr ""

#: ../engine/objectstore/handler.py:245
#, python-format
msgid "Deleting bucket %s"
msgstr ""

#: ../engine/objectstore/handler.py:249
#, python-format
msgid "Unauthorized attempt to delete bucket %s"
msgstr ""

#: ../engine/objectstore/handler.py:273
#, python-format
msgid "Getting object: %(bname)s / %(nm)s"
msgstr ""

#: ../engine/objectstore/handler.py:276
#, python-format
msgid "Unauthorized attempt to get object %(nm)s from bucket %(bname)s"
msgstr ""

#: ../engine/objectstore/handler.py:296
#, python-format
msgid "Putting object: %(bname)s / %(nm)s"
msgstr ""

#: ../engine/objectstore/handler.py:299
#, python-format
msgid "Unauthorized attempt to upload object %(nm)s to bucket %(bname)s"
msgstr ""

#: ../engine/objectstore/handler.py:318
#, python-format
msgid "Deleting object: %(bname)s / %(nm)s"
msgstr ""

#: ../engine/objectstore/handler.py:322
#, python-format
msgid "Unauthorized attempt to delete object %(nm)s from bucket %(bname)s"
msgstr ""

#: ../engine/objectstore/handler.py:396
#, python-format
msgid "Not authorized to upload image: invalid directory %s"
msgstr ""

#: ../engine/objectstore/handler.py:404
#, python-format
msgid "Not authorized to upload image: unauthorized bucket %s"
msgstr ""

#: ../engine/objectstore/handler.py:409
#, python-format
msgid "Starting image upload: %s"
msgstr ""

#: ../engine/objectstore/handler.py:423
#, python-format
msgid "Not authorized to update attributes of image %s"
msgstr ""

#: ../engine/objectstore/handler.py:431
#, python-format
msgid "Toggling publicity flag of image %(image_id)s %(newstatus)r"
msgstr ""

#. other attributes imply update
#: ../engine/objectstore/handler.py:436
#, python-format
msgid "Updating user fields on image %s"
msgstr ""

#: ../engine/objectstore/handler.py:450
#, python-format
msgid "Unauthorized attempt to delete image %s"
msgstr ""

#: ../engine/objectstore/handler.py:455
#, python-format
msgid "Deleted image: %s"
msgstr ""

#: ../engine/auth/manager.py:277
#, python-format
msgid "Looking up user: %r"
msgstr ""

#: ../engine/auth/manager.py:281
#, python-format
msgid "Failed authorization for access key %s"
msgstr ""

#: ../engine/auth/manager.py:264
#, python-format
msgid "No user found for access key %s"
msgstr ""

#: ../engine/auth/manager.py:287
#, python-format
msgid "Using project name = user name (%s)"
msgstr ""

#: ../engine/auth/manager.py:294
#, python-format
msgid "failed authorization: no project named %(pjid)s (user=%(uname)s)"
msgstr ""

#: ../engine/auth/manager.py:279
#, python-format
msgid "No project called %s could be found"
msgstr ""

#: ../engine/auth/manager.py:303
#, python-format
msgid ""
"Failed authorization: user %(uname)s not admin and not member of project "
"%(pjname)s"
msgstr ""

#: ../engine/auth/manager.py:289
#, python-format
msgid "User %(uid)s is not a member of project %(pjid)s"
msgstr ""

#: ../engine/auth/manager.py:314 ../engine/auth/manager.py:336
#, python-format
msgid "Invalid signature for user %s"
msgstr ""

#: ../engine/auth/manager.py:299 ../engine/auth/manager.py:310
msgid "Signature does not match"
msgstr ""

#: ../engine/auth/manager.py:428
msgid "Must specify project"
msgstr ""

#: ../engine/auth/manager.py:414
#, python-format
msgid "The %s role can not be found"
msgstr ""

#: ../engine/auth/manager.py:416
#, python-format
msgid "The %s role is global only"
msgstr ""

#: ../engine/auth/manager.py:469
#, python-format
msgid "Adding role %(role)s to user %(uid)s in project %(pid)s"
msgstr ""

#: ../engine/auth/manager.py:472
#, python-format
msgid "Adding sitewide role %(role)s to user %(uid)s"
msgstr ""

#: ../engine/auth/manager.py:498
#, python-format
msgid "Removing role %(role)s from user %(uid)s on project %(pid)s"
msgstr ""

#: ../engine/auth/manager.py:501
#, python-format
msgid "Removing sitewide role %(role)s from user %(uid)s"
msgstr ""

#: ../engine/auth/manager.py:574
#, python-format
msgid "Created project %(name)s with manager %(manager_user)s"
msgstr ""

#: ../engine/auth/manager.py:592
#, python-format
msgid "modifying project %s"
msgstr ""

#: ../engine/auth/manager.py:604
#, python-format
msgid "Adding user %(uid)s to project %(pid)s"
msgstr ""

#: ../engine/auth/manager.py:625
#, python-format
msgid "Remove user %(uid)s from project %(pid)s"
msgstr ""

#: ../engine/auth/manager.py:655
#, python-format
msgid "Deleting project %s"
msgstr ""

#: ../engine/auth/manager.py:713
#, python-format
msgid "Created user %(rvname)s (admin: %(rvadmin)r)"
msgstr ""

#: ../engine/auth/manager.py:722
#, python-format
msgid "Deleting user %s"
msgstr ""

#: ../engine/auth/manager.py:732
#, python-format
msgid "Access Key change for user %s"
msgstr ""

#: ../engine/auth/manager.py:734
#, python-format
msgid "Secret Key change for user %s"
msgstr ""

#: ../engine/auth/manager.py:736
#, python-format
msgid "Admin status set to %(admin)r for user %(uid)s"
msgstr ""

#: ../engine/auth/manager.py:781
#, python-format
msgid "No vpn data for project %s"
msgstr ""

#: ../engine/service.py:141
#, python-format
msgid "Starting %(topic)s node (version %(vcs_string)s)"
msgstr ""

#: ../engine/service.py:232
msgid "Service killed that has no database entry"
msgstr ""

#: ../engine/service.py:269
msgid "The service database object disappeared, Recreating it."
msgstr ""

#: ../engine/service.py:284
msgid "Recovered model server connection!"
msgstr ""

#: ../engine/service.py:290
msgid "model server went away"
msgstr ""

#: ../engine/auth/ldapdriver.py:174
#, python-format
msgid "LDAP user %s already exists"
msgstr ""

#: ../engine/auth/ldapdriver.py:205
#, python-format
msgid "LDAP object for %s doesn't exist"
msgstr ""

#: ../engine/auth/ldapdriver.py:348
#, python-format
msgid "User %s doesn't exist"
msgstr ""

#: ../engine/auth/ldapdriver.py:472
#, python-format
msgid "Group can't be created because group %s already exists"
msgstr ""

#: ../engine/auth/ldapdriver.py:478
#, python-format
msgid "Group can't be created because user %s doesn't exist"
msgstr ""

#: ../engine/auth/ldapdriver.py:495
#, python-format
msgid "User %s can't be searched in group because the user doesn't exist"
msgstr ""

#: ../engine/auth/ldapdriver.py:507
#, python-format
msgid "User %s can't be added to the group because the user doesn't exist"
msgstr ""

#: ../engine/auth/ldapdriver.py:510 ../engine/auth/ldapdriver.py:521
#, python-format
msgid "The group at dn %s doesn't exist"
msgstr ""

#: ../engine/exception.py:785
#, python-format
msgid "User %(uid)s is already a member of the group %(group_dn)s"
msgstr ""

#: ../engine/auth/ldapdriver.py:524
#, python-format
msgid ""
"User %s can't be removed from the group because the user doesn't exist"
msgstr ""

#: ../engine/auth/ldapdriver.py:528
#, python-format
msgid "User %s is not a member of the group"
msgstr ""

#: ../engine/auth/ldapdriver.py:621
#, python-format
msgid ""
"Attempted to remove the last member of a group. Deleting the group at %s "
"instead."
msgstr ""

#: ../engine/auth/ldapdriver.py:549
#, python-format
msgid "User %s can't be removed from all because the user doesn't exist"
msgstr ""

#: ../engine/auth/ldapdriver.py:564
#, python-format
msgid "Group at dn %s doesn't exist"
msgstr ""

#: ../engine/virt/xenapi/network_utils.py:55
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr ""

#: ../engine/virt/xenapi/network_utils.py:58
#, python-format
msgid "Found no network for bridge %s"
msgstr ""

#: ../engine/api/ec2/admin.py:145
#, python-format
msgid "Creating new user: %s"
msgstr ""

#: ../engine/api/ec2/admin.py:153
#, python-format
msgid "Deleting user: %s"
msgstr ""

#: ../engine/api/ec2/admin.py:175
#, python-format
msgid "Adding role %(role)s to user %(user)s for project %(project)s"
msgstr ""

#: ../engine/api/ec2/admin.py:179
#, python-format
msgid "Adding sitewide role %(role)s to user %(user)s"
msgstr ""

#: ../engine/api/ec2/admin.py:185
#, python-format
msgid "Removing role %(role)s from user %(user)s for project %(project)s"
msgstr ""

#: ../engine/api/ec2/admin.py:189
#, python-format
msgid "Removing sitewide role %(role)s from user %(user)s"
msgstr ""

#: ../engine/api/ec2/admin.py:194 ../engine/api/ec2/admin.py:271
msgid "operation must be add or remove"
msgstr ""

#: ../engine/api/ec2/admin.py:207
#, python-format
msgid "Getting x509 for user: %(name)s on project: %(project)s"
msgstr ""

#: ../engine/api/ec2/admin.py:225
#, python-format
msgid "Create project %(name)s managed by %(manager_user)s"
msgstr ""

#: ../engine/api/ec2/admin.py:238
#, python-format
msgid "Modify project: %(name)s managed by %(manager_user)s"
msgstr ""

#: ../engine/api/ec2/admin.py:248
#, python-format
msgid "Delete project: %s"
msgstr ""

#: ../engine/api/ec2/admin.py:262
#, python-format
msgid "Adding user %(user)s to project %(project)s"
msgstr ""

#: ../engine/api/ec2/admin.py:266
#, python-format
msgid "Removing user %(user)s from project %(project)s"
msgstr ""
